module.exports = {
	createdSuccess: "Created Successfully",
	notCreated: "User Creating Failure",
	errInCreate: "Error in Creating ",
	errorInFindingAll: "Error in Finding all data",
	errorInFindingId: "Error in Finding Id",
	errorInFindOne: "Error in FindOne",
	errorInFindAllMatch: "Error in FindAllMatch",
	errorInUpdating: "Error in Updating",
	errorInDeleting: "Error in Deleting",
	seekerUpdated: "Seeker Updated Successfully",
	seekerNotUpdated: "Seeker not update",
	seekerFounded: "Seeker Founded",
	notFound: "Not Found",
	userNotFound: "User Not Found",
	noSeeker: "No Seekers",
	updateDataSuccess: "Update Data Successfully",
	updateDataFailure: "Update Data Failure",
	notUpdated: "Not updated",
	deletedData: "Deleted Successfully",
	alreadyExited: "Already existing Value",
	alreadyExitedJob: "Already existing Job",
	jobPosted: "Job Posted Successfully",
	notDeleted: "Not Deleted",
	getDataSuccess: 'Get Data Success',
	getDataFailure: 'Get Data Failure',
	seekerNotFound: "Seeker Not Found",
	badRequest: "Invalid Data Provided",
	Not_Unique: "not_unique",
	loginSuccess: "Logged-in Successfully",
	dashboard: "This is dashboard",
	notchangedPass: "password was not changed",
	changedPassword: "password changed Successfully",
	loginFailure: "Login Failure",
	passwordsended: "Password is sended to Email",
	registerSuccess: "Registered successfully",
	passwordIncorrect: "Password is Incorrect",
	tokenSended: "Token sended Successfully",
	registerFailure: "Register Failure",
	Verified: "Verified Successfully",
	registerAlready: "Already Register",
	invalidOTP: "Invalid OTP",
	alreadyVerified: "Already Verified",
	giveInput: "Give the all Input",
	unauthorized: "Unauthorized Request",
	tokenVerifed: "Token Verified Successfully",
	otpResended: "OTP Resended",
	otpSended: "OTP Sent Successfully",
	otpVerifed: "OTP Verified Successfully",
	otpVerifedFailed: "OTP Verified Failed",
	otpNotSended: "OTP not sended",
	otpNotUpdated: "OTP not Updated",
	ext_email: "Already Existing Email Id",
	ext_mobile: "Already Existing Mobile Number",
	passwordMisMatch: "New password and confirm password mismatch.",
	passwordChangeFailed: "Password change failed.",

	institutionExpired: "Your Account Expired!!!",
	internalServerError: "Internal Server Error",
	alreadyExamTaken: "Your already completed this exam",

	inactiveStatus : "You are in Inactive status. Please contach admin."
};
